/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    videos: Video;
    submissions: Submission;
    modules: Module;
    lessons: Lesson;
    assignments: Assignment;
    courses: Course;
    members: Member;
    'festival-submissions': FestivalSubmission;
    'awards-submissions': AwardsSubmission;
    'ball-categories': BallCategory;
    profiles: Profile;
    'scoring-criteria': ScoringCriterion;
    'ball-scoring-criteria': BallScoringCriterion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'festival-submissions': FestivalSubmissionsSelect<false> | FestivalSubmissionsSelect<true>;
    'awards-submissions': AwardsSubmissionsSelect<false> | AwardsSubmissionsSelect<true>;
    'ball-categories': BallCategoriesSelect<false> | BallCategoriesSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'scoring-criteria': ScoringCriteriaSelect<false> | ScoringCriteriaSelect<true>;
    'ball-scoring-criteria': BallScoringCriteriaSelect<false> | BallScoringCriteriaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
    'header-navigation': HeaderNavigation;
    'footer-navigation': FooterNavigation;
    'site-popup': SitePopup;
    'header-ticker': HeaderTicker;
    'header-actions': HeaderAction;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'header-navigation': HeaderNavigationSelect<false> | HeaderNavigationSelect<true>;
    'footer-navigation': FooterNavigationSelect<false> | FooterNavigationSelect<true>;
    'site-popup': SitePopupSelect<false> | SitePopupSelect<true>;
    'header-ticker': HeaderTickerSelect<false> | HeaderTickerSelect<true>;
    'header-actions': HeaderActionsSelect<false> | HeaderActionsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role?:
    | (
        | 'admin'
        | 'pastor'
        | 'leader'
        | 'creator'
        | 'instructor'
        | 'mentor'
        | 'staff'
        | 'volunteer'
        | 'member'
        | 'student'
        | 'viewer'
      )
    | null;
  avatarId?: string | null;
  profile?: (number | null) | Profile;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  /**
   * The user account associated with this profile.
   */
  user: number | User;
  /**
   * If unchecked, this profile will not appear in the public member directory.
   */
  isPublic?: boolean | null;
  /**
   * e.g., Independent Filmmaker | Media Student at FWC
   */
  headline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  portfolioUrl?: string | null;
  socialLinks?: {
    linkedin?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    vimeo?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  description?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  assignment: number | Assignment;
  student: number | User;
  grade?: number | null;
  feedback?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  title: string;
  lesson?: (number | null) | Lesson;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dueDate?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  module: number | Module;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  course: number | Course;
  order: number;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  instructor?: (number | null) | User;
  status?: ('draft' | 'published' | 'archived') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  user: number | User;
  membershipLevel?: ('Standard' | 'Professional' | 'Lifetime') | null;
  bio?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-submissions".
 */
export interface FestivalSubmission {
  id: number;
  projectTitle: string;
  applicant: number | User;
  category?: ('Short Film' | 'Documentary' | 'Animation' | 'Feature') | null;
  externalMediaLink?: string | null;
  status?: ('pending' | 'reviewed' | 'accepted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards-submissions".
 */
export interface AwardsSubmission {
  id: number;
  nomineeName: string;
  nominator: number | User;
  awardCategory: string;
  rationale: string;
  supportingDocuments?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ball-categories".
 */
export interface BallCategory {
  id: number;
  title: string;
  group: 'grand-prize' | 'fashion' | 'realness' | 'beauty-appeal' | 'performance' | 'runway';
  /**
   * Select the criteria that will be used to judge this category.
   */
  scoringCriteria?: (number | BallScoringCriterion)[] | null;
  prizeAmount?: number | null;
  trophyCount?: number | null;
  isDuoCategory?: boolean | null;
  description?: string | null;
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  externalNotes?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the weighted rubrics used by judges for specific category groups.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ball-scoring-criteria".
 */
export interface BallScoringCriterion {
  id: number;
  /**
   * e.g., "Mr. & Miss IMA (Best Dressed Duo)", "Fashion Categories"
   */
  title: string;
  targetCategoryGroup: 'grand-prize' | 'fashion' | 'realness' | 'beauty-appeal' | 'performance' | 'runway';
  instructions?: string | null;
  rubric?:
    | {
        criterionName: string;
        weight: number;
        /**
         * Briefly explain what judges should look for in this specific criterion.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoring-criteria".
 */
export interface ScoringCriterion {
  id: number;
  /**
   * e.g., Technique, Creativity, Stage Presence
   */
  title: string;
  /**
   * Which industry/context does this criteria apply to?
   */
  association: ('ballroom' | 'film')[];
  /**
   * Explain what judges should look for when scoring this specific criteria.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'festival-submissions';
        value: number | FestivalSubmission;
      } | null)
    | ({
        relationTo: 'awards-submissions';
        value: number | AwardsSubmission;
      } | null)
    | ({
        relationTo: 'ball-categories';
        value: number | BallCategory;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'scoring-criteria';
        value: number | ScoringCriterion;
      } | null)
    | ({
        relationTo: 'ball-scoring-criteria';
        value: number | BallScoringCriterion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  avatarId?: T;
  profile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  assignment?: T;
  student?: T;
  grade?: T;
  feedback?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  order?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  module?: T;
  content?: T;
  order?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  title?: T;
  lesson?: T;
  instructions?: T;
  dueDate?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  instructor?: T;
  status?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  user?: T;
  membershipLevel?: T;
  bio?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-submissions_select".
 */
export interface FestivalSubmissionsSelect<T extends boolean = true> {
  projectTitle?: T;
  applicant?: T;
  category?: T;
  externalMediaLink?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards-submissions_select".
 */
export interface AwardsSubmissionsSelect<T extends boolean = true> {
  nomineeName?: T;
  nominator?: T;
  awardCategory?: T;
  rationale?: T;
  supportingDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ball-categories_select".
 */
export interface BallCategoriesSelect<T extends boolean = true> {
  title?: T;
  group?: T;
  scoringCriteria?: T;
  prizeAmount?: T;
  trophyCount?: T;
  isDuoCategory?: T;
  description?: T;
  requirements?: T;
  externalNotes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  isPublic?: T;
  headline?: T;
  bio?: T;
  location?: T;
  portfolioUrl?: T;
  socialLinks?:
    | T
    | {
        linkedin?: T;
        instagram?: T;
        twitter?: T;
        vimeo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoring-criteria_select".
 */
export interface ScoringCriteriaSelect<T extends boolean = true> {
  title?: T;
  association?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ball-scoring-criteria_select".
 */
export interface BallScoringCriteriaSelect<T extends boolean = true> {
  title?: T;
  targetCategoryGroup?: T;
  instructions?: T;
  rubric?:
    | T
    | {
        criterionName?: T;
        weight?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global configuration and site-specific overrides for the IMA network.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  globalOrgName: string;
  contactEmail: string;
  contactPhone?: string | null;
  globalMailingAddress?: string | null;
  /**
   * Fallback hero image if a site-specific one is not provided.
   */
  defaultHeroImage?: (number | null) | Media;
  sites?:
    | {
        siteId: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        siteName: string;
        logoLight?: (number | null) | Media;
        logoDark?: (number | null) | Media;
        favicon?: (number | null) | Media;
        seo?: {
          metaTitle?: string | null;
          metaDescription?: string | null;
          ogImage?: (number | null) | Media;
        };
        systemState?: {
          maintenanceMode?: boolean | null;
          maintenanceMessage?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  googleAnalyticsId?: string | null;
  metaPixelId?: string | null;
  /**
   * Your project token (starts with phc_...)
   */
  posthogApiKey?: string | null;
  /**
   * Usually https://us.i.posthog.com or https://eu.i.posthog.com
   */
  posthogHostUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-navigation".
 */
export interface HeaderNavigation {
  id: number;
  /**
   * Create a distinct navigation bar for each individual site.
   */
  siteNavigations?:
    | {
        site: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        items?:
          | {
              label: string;
              type?: ('link' | 'dropdown' | 'megaMenu') | null;
              url?: string | null;
              newTab?: boolean | null;
              children?:
                | {
                    label: string;
                    url: string;
                    newTab?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              megaMenu?: {
                columns?:
                  | {
                      title?: string | null;
                      links?:
                        | {
                            label: string;
                            url: string;
                            description?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                    }[]
                  | null;
                featuredCallout?: {
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  callToActionUrl?: string | null;
                  callToActionLabel?: string | null;
                };
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-navigation".
 */
export interface FooterNavigation {
  id: number;
  /**
   * Configure the footer structure independently for each site.
   */
  siteFooters?:
    | {
        site: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        columns?:
          | {
              title: string;
              links?:
                | {
                    label: string;
                    url: string;
                    newTab?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        socialLinks?:
          | {
              platform: 'instagram' | 'twitter' | 'facebook' | 'linkedin' | 'tiktok' | 'youtube';
              url: string;
              id?: string | null;
            }[]
          | null;
        bottomLegalLinks?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage modal popups for newsletter signups, ticket sales, or major announcements across the IMA network.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-popup".
 */
export interface SitePopup {
  id: number;
  /**
   * Configure popups independently for each site.
   */
  sitePopups?:
    | {
        site: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        isActive?: boolean | null;
        displayRules?: {
          showOn?: ('all' | 'specific') | null;
          /**
           * Enter the exact URL paths where this popup should appear. (e.g., "/" for Home, "/categories" for the Roster page).
           */
          targetPaths?:
            | {
                path: string;
                id?: string | null;
              }[]
            | null;
          frequency?: ('always' | 'once-per-session' | 'once-ever') | null;
          /**
           * How long to wait before showing the popup.
           */
          delaySeconds?: number | null;
        };
        content: {
          image?: (number | null) | Media;
          title: string;
          description?: string | null;
          ctaLabel?: string | null;
          ctaUrl?: string | null;
          /**
           * If checked, your Next.js frontend should render an email input form instead of a standard button.
           */
          isNewsletterSignup?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the scrolling announcement marquee at the top of each site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-ticker".
 */
export interface HeaderTicker {
  id: number;
  /**
   * Create and manage tickers independently for each site in the network.
   */
  siteTickers?:
    | {
        site: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        isActive?: boolean | null;
        /**
         * Add the text phrases that will continuously scroll across the screen (e.g., "Legends Never Die"). They will be separated by a decorative star/icon on the frontend.
         */
        messages?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * If provided, clicking anywhere on the scrolling marquee will redirect the user.
         */
        link?: {
          url?: string | null;
          newTab?: boolean | null;
        };
        appearance?: {
          /**
           * e.g., #FFE74C. Leave blank to use site default.
           */
          backgroundColorHex?: string | null;
          /**
           * e.g., #170F11. Leave blank to use site default.
           */
          textColorHex?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Call-To-Action (CTA) buttons displayed on the right side of the main navigation bar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-actions".
 */
export interface HeaderAction {
  id: number;
  /**
   * Configure CTAs independently for each site.
   */
  siteActions?:
    | {
        site: 'ima' | 'heritage-ball' | 'imf' | 'gala';
        buttons?:
          | {
              label: string;
              url: string;
              variant?: ('primary' | 'outline') | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  globalOrgName?: T;
  contactEmail?: T;
  contactPhone?: T;
  globalMailingAddress?: T;
  defaultHeroImage?: T;
  sites?:
    | T
    | {
        siteId?: T;
        siteName?: T;
        logoLight?: T;
        logoDark?: T;
        favicon?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              ogImage?: T;
            };
        systemState?:
          | T
          | {
              maintenanceMode?: T;
              maintenanceMessage?: T;
            };
        id?: T;
      };
  googleAnalyticsId?: T;
  metaPixelId?: T;
  posthogApiKey?: T;
  posthogHostUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-navigation_select".
 */
export interface HeaderNavigationSelect<T extends boolean = true> {
  siteNavigations?:
    | T
    | {
        site?: T;
        items?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              newTab?: T;
              children?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              megaMenu?:
                | T
                | {
                    columns?:
                      | T
                      | {
                          title?: T;
                          links?:
                            | T
                            | {
                                label?: T;
                                url?: T;
                                description?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    featuredCallout?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          image?: T;
                          callToActionUrl?: T;
                          callToActionLabel?: T;
                        };
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-navigation_select".
 */
export interface FooterNavigationSelect<T extends boolean = true> {
  siteFooters?:
    | T
    | {
        site?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        bottomLegalLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-popup_select".
 */
export interface SitePopupSelect<T extends boolean = true> {
  sitePopups?:
    | T
    | {
        site?: T;
        isActive?: T;
        displayRules?:
          | T
          | {
              showOn?: T;
              targetPaths?:
                | T
                | {
                    path?: T;
                    id?: T;
                  };
              frequency?: T;
              delaySeconds?: T;
            };
        content?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              isNewsletterSignup?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-ticker_select".
 */
export interface HeaderTickerSelect<T extends boolean = true> {
  siteTickers?:
    | T
    | {
        site?: T;
        isActive?: T;
        messages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              url?: T;
              newTab?: T;
            };
        appearance?:
          | T
          | {
              backgroundColorHex?: T;
              textColorHex?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-actions_select".
 */
export interface HeaderActionsSelect<T extends boolean = true> {
  siteActions?:
    | T
    | {
        site?: T;
        buttons?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}